import 'package:get/get.dart';
import 'package:standard_project/module/grade/academic/data/model/academic.dart';
import 'package:standard_project/module/grade/academic/data/repo/academic_repo.dart';

class AcademicController extends GetxController with AcademicRepo {
  List<academicmodel> academiclist = [
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    academicmodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
  ];
}
