import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:standard_project/module/study/data/model/study.dart';
import 'package:standard_project/module/study/data/repo/study_repo.dart';

class StudyController extends GetxController with StudyRepo {
  TextEditingController searchTextfieldController = TextEditingController();
  String searchField = '';

  List<Studymodel> studylist = [
    Studymodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20022",
      NamaMatakuliah: "Microprocessor",
      SKS: "2",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
    Studymodel(
      No: "1",
      KodeMatakuliah: "20028",
      NamaMatakuliah: "Kalkulus",
      SKS: "1",
      UTS: "90",
      UAS: "90",
      NilaiHuruf: "A",
      NilaiAngka: "3.9",
    ),
  ];
}
